### ISSUE TITLE
Deliverable 3

### ISSUE THREAD

**Issue by Senseiswiss** [bazenmekonen/IS436_Group_Project#6]
https://github.com/bazenmekonen/IS436_Group_Project/blob/main/Deliverable%203.pdf
https://github.com/bazenmekonen/IS436_Group_Project/blob/main/Deliverable%2B3%2B-%2BPresentation%2B.pptx.pdf

**Comment by bazenmekonen** [comment]
Paper is finished

**Comment by bazenmekonen** [comment]
Slides are finished
